cmd/bom/cmd/generate.go, pkg/spdx/builder.go, pkg/spdx/file.go, pkg/spdx/implementation.go, pkg/spdx/object.go, pkg/spdx/package.go, pkg/spdx/spdx.go, pkg/spdx/spdx_unit_test.go, pkg/spdx/spdxfakes/fake_spdx_implementation.go
/kind bug
/kind cleanup
/kind feature
/kind deprecation
This PR adds a bunch of improvements to the bom tool and the spdx libraries:
* Adds a few more unit tests to the `spdx` package to cover the following functions:
* `spdx.GetImageReferences`
* `spdx.TestPullImagesToArchive`
* `spdx.TestGetDirectoryTree`
* `spdx.TestIgnorePatterns`
* The `--tarballs` flag is now deprecated. It has been replaced with `--image-archive` during demos and chats, it proved to be confusing (it still works but will print a warning)
* There is a new flag `--archive` that adds archives (currently tars) as packages. Its files are license-scanned and listed in the package
* Passing a flag defining the SPDX document namespace is not required anymore. The generator now defines it using the spdx.org public URL …
=> Support archives as package src, autonamespace and other improvements

pkg/spdx/file.go, pkg/spdx/file_test.go
/kind feature
- add initial filetype support
https://spdx.github.io/spdx-spec/file-information/#83-file-type-field
/assign @puerco @justaugustus @saschagrunert 
```
$ ./main generate -f RELEASE.md
INFO Generating SPDX Bill of Materials
INFO Processing file RELEASE.md
WARN Document has no name defined, automatically set to SBOM-SPDX-800a2e0e-6a1b-44e2-aa69-1ef3fa936a9e
SPDXVersion: SPDX-2.2
DataLicense: CC0-1.0
SPDXID: SPDXRef-DOCUMENT
DocumentName: SBOM-SPDX-800a2e0e-6a1b-44e2-aa69-1ef3fa936a9e
DocumentNamespace: https://spdx.org/spdxdocs/k8s-releng-bom-9ec315ad-fe71-44de-a8b9-e0cbaf057a84
Creator: Tool: sigs.k8s.io/bom/pkg/spdx
Created: 2021-12-22T15:43:46Z
FileName: RELEASE.md
SPDXID: SPDXRef-File-RELEASE.md
FileChecksum: SHA1: …
```
=> add initial filetype support

pkg/license/license_unit_test.go, pkg/spdx/document_unit_test.go
/kind cleanup
- update license test by removing duplicate test file
windows and mac do see files with the same name but different caps all the same like LICENSE and license are the same file then the tests will fail for those platforms, skipping the tests if that run on mac/windows
/assign @puerco @xmudrii @Verolop 
None
```release-note
NONE
```
=> update license test by removing duplicate test file

pkg/spdx/implementation.go
Use the default Docker keychain to leverage auth mechanisms so that we can allow users to work with non-public remote images.
Resolves #17
```release-note
Use the default Docker keychain to leverage auth mechanisms so that we can allow users to work with non-public remote images.
```
=> Enable generate on non-public, remote images

pkg/spdx/document_unit_test.go
/kind failing-test
/kind flake
The `TestToProvenance` test was flaking because the order of the provenance subjects was unpredictable causing `require.Equal` to fail to match the SUT against the known example.
The same flake was happening in `TestWriteProvenance`. So a second commit introduces a function to compare
provenance Subjects that both tests share.
This change modifies the check to compare the Subject hashes one by one and avoid the 1/3 chance that the test would flake.
Related to flakes in https://github.com/kubernetes-sigs/bom/pull/24 and https://github.com/kubernetes-sigs/bom/pull/18
```release-note
Fixed flakes in `TestWriteProvenance` and `TestToProvenance` where the test would fail one every three runs
```
=> Fix flake in TestToProvenance and TestWriteProvenance

go.mod, magefile.go, pkg/license/catalog.go, pkg/license/download.go, pkg/license/license.go, pkg/provenance/statement.go, pkg/spdx/builder.go, pkg/spdx/document_unit_test.go, pkg/spdx/imageanalyzer.go, pkg/spdx/object.go, pkg/spdx/spdx_unit_test.go, scripts/verify-build.sh
/kind cleanup
/kind feature
- general go import updates to organize it
- fix the build command to build the `bom` binaries 
- add clean mage command 
now can use
```shell
$ mage build
Running go build...
Building project for linux/amd64
Building project for linux/arm64
Building project for darwin/amd64
Building project for darwin/arm64
Building project for windows/amd64
Binaries available in the output directory.
$ ./output/bom-darwin-amd64 --help
bom (Bill of Materials)
....
```
/assing @puerco @justaugustus @saschagrunert 
None
```release-note
NONE
```
=> go imports update and fix mage build command

cmd/bom/cmd/root.go, cmd/bom/cmd/version.go, magefile.go, pkg/version/version.go, pkg/version/version_test.go, scripts/verify-build.sh
/kind feature
- add version command and ldflags
to help in debug and inform the user which version they are using
```
$ ./output/bom-darwin-amd64 version
______  ________  ___
| ___ \|  _  |  \/  |
| |_/ /| | | | .  . |
| ___ \| | | | |\/| |
| |_/ /\ \_/ / |  | |
\____/  \___/\_|  |_/
bom: A tool for working with SPDX manifests
GitVersion:    v0.1.0-64-ga8d39d8
GitCommit:     a8d39d8
GitTreeState:  dirty
BuildDate:     2022-01-22T17:25:52Z
GoVersion:     go1.17.6
Compiler:      gc
Platform:      darwin/amd64
```
/assign @puerco @justaugustus @xmudrii @Verolop @saschagrunert 
```release-note
```
=> add version command and ldflags

cmd/bom/cmd/generate.go, pkg/spdx/builder.go, pkg/spdx/implementation.go, pkg/spdx/spdx.go
/kind bug
/kind cleanup
/kind feature
This PR has 3 parts:
1. Adds a new flag `--name` to allow the user to specify the name used in the document, if left blank it gets autogenerated
2. Adds a new flag `--scan-images` that determine if images are scanned for OS information
3. Introduces a new check where all arguments that take files and directories as arguments will be checked for existence before starting to generate the SBOM.
Thanks @kfaseela for sharing your use case!
None
```release-note
- Files and directories passed in flags to the bom utility are now checked for existence before running the SBOM generator
- New flag `--name` allows thew user to set the document name from the command line
- New flag `--scan-images` controls if container images are scanned for OS packages or not
```
=> generate: Add --name --scan-images and check files early

pkg/osinfo/layer_scanner.go, pkg/spdx/builder.go, pkg/spdx/implementation.go
/kind bug
This PR fixes two bugs:
1. Compressed tarballs are now autodetected and correctly handled by checking the first bytes in the header.  
2. There was a missing bit in the new --scan-images flag that missed some plumbing. Fixed now.
Fixes #36
```release-note
- Tarball headers are now checked to see if they are compressed. Previously we relied on file extensions which made the tarball handling code flaky
- Fixed a proble where `--scan-images` was unresponsive because a bug in the internal plumbing 
```
=> Autodetect compressed tarballs and fix --scan-images flag

scripts/verify-build.sh
/kind bug
The build script called by the magefile was producing dynamic executables. 
This commit disables cgo to produce static binaries.
Signed-off-by: Adolfo García Veytia <adolfo.garcia@uservers.net>
None
/assign @cpanato 
```release-note
released `bom` binaries are now statically compiled
```
=> Disable cgo in build script

pkg/spdx/builder.go
/kind feature
This commit adds support for adding archives to the SBOM from
the YAML configuration file. All other artifacts were already
supported but archives are a newer kind and had not been added yet.
None
Sample configuration:
```yaml
---
namespace: https://example.com/
license: Apache-2.0
name: myproject
artifacts:
- type: archive
source: file.tar
```
```release-note
The YAML configuration file now supports adding archives using `type: archive`
```
=> builder: Support archives in config

cmd/bom/cmd/generate.go
/kind cleanup
It helps a lot to debug when generating an SBOM if you know
the bom version you are running. This change modifies the
first log output so that it gets written to the CI/CD log:
```
bom VERSION: Generating SPDX Bill of Materials
```
None
```release-note
When generating an SBOM, `bom` will now print its version before running to record it in CI/CD logs
```
=> generate: Print bom version when running

cmd/bom/cmd/document.go
Signed-off-by: jeremyrickard <jeremyrrickard@gmail.com>
/kind bug
/kind cleanup
This PR updates the `document outline` command to show help when no file is provided. It also updates the usage string to show the required positional argument:
```
./bom document outline
bom document outline → Draw structure of a SPDX document",
This subcommand draws a tree-like outline to help the user visualize
the structure of the bom. Even when an SBOM represents a graph structure,
drawing a tree helps a lot to understand what is contained in the document.
You can define a level of depth to limit the expansion of the entities.
For example set --depth=1 to only visualize only the files and packages
attached directly to the root of the document.
bom will try to add useful information to the oultine but, if …
```
=> Update and show help on missing file for outline subcommand

pkg/spdx/implementation.go
/kind bug
This PR adds a validation for cases where the directory passed in for --dirs argument does not have any files left to scan after applying the ignore pattern. Without this check, bom generate gives an error like below which was not so clear to debug.
FATA generating doc: writing doc to ./out/istio-release.spdx: generating document markup: rendering pkg out: unable to get package verification code, package has no files
=> Add validation for empty directories

pkg/spdx/builder.go, pkg/spdx/document.go, pkg/spdx/document_unit_test.go, pkg/spdx/file.go, pkg/spdx/object.go, pkg/spdx/package.go, pkg/spdx/spdx.go, pkg/spdx/spdx_unit_test.go
/kind feature
/kind bug
This pull request introduces a new function to the document, File and Package objects to search for elements. This is inspired by the XML/HTML DOM and is called `document.GetElementByID()`. 
Passing an SPDX identifier to the function will return the element that matches the ID or nil if its not found.
**Bonus:** Leveraging these functions, we now ensure that packages generated from any source (dirs, images, etc) get unique IDs. Previously we tried to avoid name clashes by generating names hierarchically but that approach proved insufficient frequently.
None
Unit tests for the new functions are included.
```release-note
- New XML-DOM inspired `x.GetElementByID()` allows querying documents, Files and Packages for elements that match an ID.
- The builder Object now …
```
=> Make the document queryable (and ensure unique names)

cmd/bom/cmd/root.go, cmd/bom/cmd/validate.go, go.mod, go.sum, pkg/spdx/document.go, pkg/spdx/document_unit_test.go, pkg/spdx/spdx.go
/kind feature
This PR introduces to bom the capability to start validating things. For now, only files attached to the first level of the document are supported and we will be introducing more artifact types and other kinds of validation.
None
~~Test for `document.ValidateFiles()` is coming in a followup shortly~~
Test is now included
/assign @cpanato 
```release-note
`bom` can now validate artifacts! We now have a new validate subcommand that can be used to check files attached to the top of the SBOM: `bom validate sbom.spdx file.txt`. No more checksum.txt files! 🎉
```
=> Validate Subcommand!

pkg/spdx/document.go, pkg/spdx/file.go, pkg/spdx/object.go, pkg/spdx/package.go, pkg/spdx/parser.go
/kind bug
/kind cleanup
/kind feature
This commit enables the parser to read SBOMs from STDIN when specifying the SBOM path as `-`. When - is detected as filename, bom will buffer the SBOM to stdin and parse it from there.
In addition this PR adds support for some missing tags to both the parser and renderer:
- `PackageSupplier`
- `LicenseComments` and `PackageLicenseComments`
- `PackageHomePage`
It also fixes a bug where a document's creator organization was missing from the SBOM.
None
/assign @cpanato @jeremyrickard 
```release-note
- SBOMs can now be read from STDIN by passing `-` as a path wherever a filename is expected
- Added support to render and parse `PackageSupplier`, `PackageHomePage`, `LicenseComments` and `PackageLicenseComments`
- Fixed a bug where the creator organization …
```
=> Support Parsing SBOMs from STDIN

magefile.go
/kind bug
/kind cleanup
- update golangci-lint
- fix ldflags when building the images with ko
- remove conflict ko flag
follow up of https://github.com/kubernetes-sigs/bom/pull/45
/assign @saschagrunert @puerco 
None
```release-note
NONE
```
=> Fix image build command

cloudbuild.yaml, magefile.go
/kind bug
using the --bare flag we need to set the KO_DOCKER_REPO for the full name
also update ko to the latest release
run this on my gcp account and now everything works, sorry was my mistake
/assign @saschagrunert @puerco 
None
```release-note
NONE
```
=> update ko command

cmd/bom/cmd/document.go, cmd/bom/cmd/generate.go, cmd/bom/cmd/root.go
/kind cleanup
Addressing @jeremyrickard 's comment here: https://github.com/kubernetes-sigs/bom/pull/46#discussion_r796239490 ,  
this command refactors the rest of the cli to make commands reusable. Now all share the same pattern.
/assign @jeremyrickard @cpanato 
Follow-up to #46
```release-note
Cobra commands in the CLI now can be reused and now share the same import pattern
```
=> generate+document commands refactor

go.mod, go.sum, pkg/osinfo/container_scanner.go, pkg/osinfo/container_scanner_test.go, pkg/osinfo/layer_scanner.go, pkg/spdx/gomod.go, pkg/spdx/gomod_test.go, pkg/spdx/implementation.go, pkg/spdx/package.go
/kind feature
bom will now annotate system packages, golang dependencies and OCI images (in a registry) with a [package URL](https://github.com/package-url/purl-spec). Reading this annotation makes it easier to detect what kind of source the spdx package is describing.
Having purls in all artifacts will now allow answering questions like _Does this SBOM describe an image?, do we have golang dependency information? what about the system packages in this image?_ 
None
Sample run:
```
go run cmd/bom/main.go generate --image=nginx | grep purl
ExternalRef: PACKAGE-MANAGER purl pkg:oci/nginx@sha256:1c13bc6de5dfca749c377974146ac05256791ca2fe1979fc8e8278bf0121d285?repository_url=index.docker.io%2Flibrary&tag=nginx
ExternalRef: PACKAGE-MANAGER purl …
```
=> Generate purls from read sources

go.mod, go.sum, pkg/spdx/implementation.go
Fixes #72
/kind bug
It will check local image cache before trying to pull image from registry
Fixes #72
```release-note
fix: check local image cache first 
```
=> fix: check local image cache first

cmd/bom/cmd/document.go, pkg/osinfo/container_scanner.go
/kind bug
This PR fixes two bugs in bom:
Fixes a panic where `bom` would die when no OS packages could be read from a debian base layer.
It also fixes a bug that disconnected the entire document subcommand during the last command refactor
```release-note
- Fixed a panic where `bom` would die when no OS packages could be read from a debian base layer.
- Fixed a bug that disconnected the entire document subcommand from the main cobra command
```
=> Fix panic when emtpy os deps, readd document

cloudbuild.yaml
/kind cleanup
the image `gcr.io/k8s-staging-releng/releng-ci:latest-go1.17` is not being generated and that image has go 1.17rc2 we now build two configs for the latest tag:
- `gcr.io/k8s-staging-releng/releng-ci:latest-go1.17-bullseye`
- `gcr.io/k8s-staging-releng/releng-ci:latest-go1.17-buster`
let's use the one with the bullseye for now
to show that we are building bom with 1.17rc2
```
$ docker run gcr.io/k8s-staging-bom/bom:dcaf425 version
Unable to find image 'gcr.io/k8s-staging-bom/bom:dcaf425' locally
dcaf425: Pulling from k8s-staging-bom/bom
b0b160e41cf3: Pull complete
250c06f7c38e: Pull complete
2be54ece9dd9: Pull complete
Digest: sha256:f16abe64f52e60b519c0acfc205f955e6d304a8529282393ff12f437ff86833c
Status: Downloaded newer image for gcr.io/k8s-staging-bom/bom:dcaf425
____ …
```
=> update build image to use latest go

canary/manifests/k8s-staging-bom/promoter-manifest.yaml
Test specifying the service account in the promo manifest
```release-note
NONE
```
=> Specify SVC account in promo manifest

canary/images/k8s-staging-bom/images.yaml, canary/manifests/k8s-staging-bom/promoter-manifest.yaml
/kind cleanup
This PR removes the test image promotion manifests we had set up to build canary images for bom. The manifests now live in k8s-sigs/promo-tools.
/assign @cpanato 
```release-note
The bom project now features canary releases published to the staging bucket
```
=> Delete canary builds manifests

pkg/spdx/gomod.go, pkg/spdx/implementation.go
/kind bug
This PR fixes three bugs in the go dependency code:
1. It fixes a bug in the dependency generator where var scope was handled wrong and errors were not being surfaced correctly
2. It makes the go module parser more permissive preventing a fatal error when a dependency cannot be converted to a SPDX package
3. Finally, it fixes a bug where the go module being analyzed was listed as a dependency 
Fixes #61
/assign @cpanato @justaugustus @saschagrunert 
```release-note
- Fixes a bug in the go dependency generator where var scope was handled wrong and errors were not being surfaced correctly
- The go module parser is now more permissive preventing a fatal error when a dependency cannot be converted to a SPDX package
- Fixed a bug where the go …
```
=> Bug fixes in go dependencies 

magefile.go, pkg/license/implementation.go, pkg/provenance/statement.go, pkg/spdx/builder.go, pkg/spdx/gomod.go, pkg/spdx/gomod_test.go, pkg/spdx/implementation.go, pkg/spdx/spdx.go
/kind cleanup
This commit modifies the way we name the spdx packages generated from go modules. We now drop the version and let
the package be named only the module import path (version is still included in the appropriate field)
```
BEFORE:
PackageName: golang.org/x/xerrors@v0.0.0-20200804184101-5ec99f83aff1
NOW:
PackageName: golang.org/x/xerrors
```
This makes the bom sbom match the way ko, apko and other tools name their packages. It also adds a new test to check the
fields generated for the package.
None
**Update:** Pushed two extra commits to fix the CI. It appears that the version of golangci-lint has a problem when running in the test environment. One bumps golangci-lint, the second goumpt-s a bunch of files …
=> Drop revision from spdx packages names generated from go modules

cmd/bom/cmd/document.go, cmd/bom/cmd/generate.go, cmd/bom/cmd/query.go, cmd/bom/cmd/validate.go
/kind cleanup
The PR updates the `cmd/bom` go packege to replace `github.com/pkg/errors dependency` with native error wrapping
Part of https://github.com/kubernetes-sigs/bom/issues/114
```release-note
NONE
```
=> cmd/bom: replace github.com/pkg/errors dependency with native error wrapping

pkg/query/engine.go
/kind cleanup
The PR updates the `pkg/query` go packege to replace `github.com/pkg/errors dependency` with native error wrapping
Part of https://github.com/kubernetes-sigs/bom/issues/114
```release-note
NONE
```
=> pkg/query: replace github.com/pkg/errors dependency with native error wrapping

pkg/license/catalog.go, pkg/license/download.go, pkg/license/implementation.go, pkg/license/license.go, pkg/license/license_test.go
/kind bug
Replaces the github.com/pkg/errors dependency with native error wrapping in the pkg/license package
#114 
None
```release-note
None
```
=> replace error handling method in pkg/license

pkg/license/catalog.go
/kind cleanup
follow up of PR #120 
#114 
None
```release-note
None
```
=> fix errors package used in pkg/license/catalog.go

cmd/bom/cmd/validate.go, pkg/spdx/document.go, pkg/spdx/parser.go
/kind feature
We now can validate whole directories rather than just a set of files.
This can be used for example like this, if we assume that `cri-o`
contains the full tarball content (the package).
```
> bom validate -e cri-o.amd64.770ae3f4be46ba4fc731836eb274f365c6e9fd85.tar.gz.spdx -d cri-o
+-----------------------------------+-------+-----------------------------+----------------+
|             FILENAME              | VALID |           MESSAGE           | INVALID HASHES |
+-----------------------------------+-------+-----------------------------+----------------+
| LICENSE                           | OK    | File validated successfully | -              |
| Makefile                          | OK    | File validated successfully | -              |
| README.md                         | …
```
=> Add dir verification support via `bom validate -d`

pkg/spdx/json/v2.2.2/types.go
/kind bug
`externalDocumentRefs` were missing from the document type. This commit adds
support for it and the corresponding struct for the references.
None
```release-note
Added `externalDocumentRefs` to the json types
```
=> Add External Document Ref to json types

.github/workflows/docs.yml, docs/config.toml
Feedback only asks to open an issue, and which is too much for the simple pages we are showing
=> Remove feedback from docs

.ko.yaml
Co-authored-by: Jason Hall <jason@chainguard.dev>
/kind feature
/kind bug
Fixes #135 
After a quick chat with @imjasonh, thanks to him, we have agreed that the best way of providing a go binary for an image that is building with ko is changing the image's base with the one of the go binary installed. Fortunately, we have one, https://github.com/distroless/go. [distroless.dev/go](http://distroless.dev/go) is an apko-built distroless image that includes go.
cc: @imjasonh
```release-note
chore: use different base image to include go
```
=> chore: use different base image to include go

pkg/spdx/implementation.go
/kind bug
This PR changes the way bom adds package names, until now we were concatenating version and name in the package name.
This is not correct, now bom will only add the name in the name field and the package version is still contained in the SBOM version field.
None
/kind bug
```release-note
Fixed a bug where Debian packages were listed in the SBOM with the version appended, now `Name` only has the name as expected
```
=> Don't concatenate name and version in os packages

go.mod, go.sum, pkg/spdx/implementation.go, pkg/spdx/spdx.go, pkg/spdx/spdxfakes/fake_spdx_implementation.go
/kind bug
This PR disables the local daemon lookup of container images to fix #134. 
When passing a reference to a multiarch image to the local docker daemon, the reference gets transalated to the local arch image, generating an SBOM only for the image corresponding to the local architecture. 
This PR reverts the local daemon change as apparently there is no way to get the docker daemon to return the correct reference (to the image index ) to GGCR.
In order to improve image download times the blob downloads to local tarballs are now parallelized which should at least provide some speed gains.
Fixes #134
```release-note
- Looking for precached images in the local daemon is now removed as it broke multiarch image SBOMs
- Image downloading is now …
```
=> Disable local cache lookup, favor parallel download

pkg/serialize/serialize.go
When the BOM was to be generated in SPDX JSON format, the external reference for PURL was missing. This PR fixes that.
Eg, a package node before PR would look like
```javascript
{
"SPDXID": "SPDXRef-Package-gomod-github.com-gogo-protobuf-v1.3.2",
"name": "github.com/gogo/protobuf",
"versionInfo": "v1.3.2",
"filesAnalyzed": false,
"licenseDeclared": "NOASSERTION",
"licenseConcluded": "BSD-3-Clause",
"downloadLocation": "https://proxy.golang.org/github.com/gogo/protobuf/@v/v1.3.2.zip",
"copyrightText": "Copyright (c) 2013, The GoGo Authors. All rights reserved.\n\nProtocol Buffers for Go with Gadgets\n\nGo support for Protocol Buffers - Google's data interchange format\n\nCopyright 2010 The Go Authors.  All rights reserved.\nhttps://github.com/golang/protobuf\n\nRedistribution and use in …
```
=> Add package url external ref in json format too

pkg/spdx/implementation.go, pkg/spdx/spdx.go, pkg/spdx/spdx_unit_test.go, pkg/spdx/spdxfakes/fake_spdx_implementation.go
/kind feature
This pull request modifies the way we capture container images in SBOMs to make our output similar to that of other tools like tern and ko. It introduces two changes:
Before this change, our package names were based on the tags of images. We now use the digests, all the information about the image is still kept in the purl of the package, so the tag data is not lost:
Image archives are now listed as tarfiles, instead of OCI artifacts. Since the archive is a tarball disconnected from a registry and its manifest is not there yet, we treat them as a file. The contents of those packages are the layers and those are they are still treated as packages, with their OCI purls.
Generating an SBOM for a single arch image was broken. This PR also fixes that and now running something …
=> Update image SBOMs to current practices

pkg/serialize/serialize.go, pkg/spdx/json/v2.2/types.go, pkg/spdx/parser.go
Signed-off-by: Brandon Lum <lumjjb@gmail.com>
/kind cleanup
/kind api-change
Simplifies the support with the release of newer SPDX versions so a new "patch" version does not need to be defined each time for the JSON struct.
None
SPDX struct definitions are tied to minor versions, patch versions are only for documentation updates, so there's no need to specify structs to the level of the patch version :). 
No, unless there are uses of the `spdx/json` pkg
```release-note
Change SPDX json package name to remove patch semantic versioning
```
=> SPDX json definition set to minor version

magefile.go
/kind bug
Fixes #151 
```release-note
fix: ko version output in magefile
```
=> fix: ko version output

magefile.go
/kind bug
followup of https://github.com/kubernetes-sigs/bom/pull/152
we need to run the version command and pass a version expected to validate.
cc @developer-guy 
/assign @saschagrunert @puerco 
```release-note
```
=> fix check against the version that we need to install

pkg/spdx/file.go
/kind bug
This PR fixes a bug where compressed tarballs did
not get their proper file type.
NONE
```release-note
Fixed a bug where `FileType` in compressed tars was not categorized as `ARCHIVE`
```
=> Fix file type of compressed tars

go.mod, pkg/license/catalog.go, pkg/license/download.go, pkg/license/license_test.go
/kind bug
This PR fixes the license package in bom to work with the latest prereleases of license classifier. The paths expected by the classifier changed, at first causing a panic fixed by @saschagrunert in https://github.com/google/licenseclassifier/pull/44 and now, we don't have the crash anymore but SBOMs are getting stuffed with junk as the traces are going to STDOUT:
```
go run ./cmd/bom/main.go generate --format=json ../chainguard/darkfiles/ 
INFO bom devel: Generating SPDX Bill of Materials 
INFO Processing directory ../chainguard/darkfiles/ 
INFO Loading license data from downloader         
INFO Downloading main SPDX license data from https://spdx.org/licenses/ 
INFO Sending GET request to https://spdx.org/licenses/licenses.json 
INFO Read data for 496 licenses. Downloading. …
```
=> Fix license package to work with latest license classiffier

.github/workflows/verify-spdx.yaml
/kind feature
This PR adds a new actions workflow to run a conformance check presubmit. New PRs will generate a set of sample SBOMs which will be run through the SPDX java tools verifier to ensure the SPDX sytax is valid.
None
Requires https://github.com/chainguard-dev/actions/pull/143 to run
```release-note
Introduced a new presubmit workflow to validate SPDX conformance check on the documents generated by bom using the SPDX java tools.
```
=> Workflow: Initial SPDX conformance check

cmd/bom/cmd/generate.go, pkg/spdx/builder.go
Without this PR:
```bash
./bom generate ./   --format json -o bom.json
```
Would output standard SPDX bom in `bom.json`, completely disregarding the `--format` flag.
This PR fixes that.
=> Fix file output with different format

cmd/bom/cmd/document.go, cmd/bom/cmd/query.go, pkg/spdx/package_test.go, pkg/spdx/parser.go
/kind feature
This allows the automatic retrieval of uRL content, for example via:
```
bom document outline https://storage.googleapis.com/kubernetes-release-gcb/release/v1.26.0-alpha.1/kubernetes-release.spdx
```
None
```release-note
Allow specifying URLs in `bom document query/outline`.
```
=> Allow specifying URLs in `document outline/query`

.github/dependabot.yml, .github/workflows/docs.yml, .github/workflows/verify-spdx.yaml, .golangci.yml, .ko.yaml, cloudbuild.yaml, cmd/bom/cmd/document.go, cmd/bom/cmd/generate.go, cmd/bom/cmd/query.go, go.mod, magefile.go, pkg/osinfo/layer_scanner.go, pkg/query/filter.go, pkg/spdx/file.go, pkg/spdx/file_test.go, pkg/spdx/imageanalyzer.go, pkg/spdx/imageanalyzer_distroless.go, pkg/spdx/imageanalyzer_gorunner.go, pkg/spdx/implementation.go, pkg/spdx/object.go, pkg/spdx/package.go, pkg/spdx/spdx.go, pkg/spdx/spdx_unit_test.go
/kind feature
- enable dependabot for github actions
- update actions
- bump go to 1.19
/assign @puerco @saschagrunert @Verolop @xmudrii 
need: https://github.com/kubernetes/test-infra/pull/27732
None
```release-note
bump go to 1.19
```
=> Upgrade go1.19

pkg/license/implementation.go, pkg/license/license.go, pkg/spdx/gomod.go
/kind bug
/kind cleanup
This PR improves the licensing code to be more resilient when encountering unexpected license tags in the
classifier output. Since v2.0.0, [the classifier will now return a pseudo license tag when finding copyright information] in files. This caused our libraries to return an error when scanning files.
It also fixes another bug where the secondary license list was lost after scanning and classifying a file. 
The verbosity of the licensing code has now been reduced to make it more understandable.
Part of https://github.com/kubernetes/release/issues/2729
/assign @jeremyrickard @xmudrii @cpanato 
```release-note
- Fixed a bug where the secondary license list returned by the classifier was not being returned
- Improved the licensing code to be more resilient to …
```
=> Make license package more resilient to unexpected output

pkg/spdx/parser.go
:
/kind bug
This commit fixes a panic in the document outliner where bom would crash when the sbom contains files at the top level of the sbom:
```
om document outline example11/spdx/sbom.spdx.json 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x85b8be]
goroutine 1 [running]:
sigs.k8s.io/bom/pkg/spdx.parseJSON(0x7ffc5908f0e5?)
sigs.k8s.io/bom/pkg/spdx/parser.go:374 +0x111e
sigs.k8s.io/bom/pkg/spdx.OpenDoc({0x7ffc5908f0e5?, 0x1d?})
sigs.k8s.io/bom/pkg/spdx/parser.go:86 +0x346
sigs.k8s.io/bom/cmd/bom/cmd.AddOutline.func1(0xc000248600?, {0xc0001efa70?, 0x1?, 0x1?})
sigs.k8s.io/bom/cmd/bom/cmd/document.go:119 +0x3f
github.com/spf13/cobra.(*Command).execute(0xc000248600, {0xc0001efa30, 0x1, 0x1}) …
```
=> Fix panic in outliner

pkg/spdx/parser.go
/kind bug
This PR fixes a bug where SBOMs could not be ingested when the supplier of a package was set to `NOASSERTION`.
Signed-off-by: Adolfo Garcia Veytia (puerco) <puerco@chainguard.dev>
/cc @jeremyrickard @xmudrii 
```release-note
Fixed a bug where SBOMs were not ingested when the supplier of a package was `NOASSERTION`.
```
=> Fix b0rk when supplier is NOASSERTION

cmd/bom/cmd/document.go, pkg/spdx/document.go, pkg/spdx/package.go
/kind feature
This PR improves the document outliner by introducing two small features:
1 . The outliner will now print versions by default along with the package names (decided from [this very scientific Twitter poll](https://twitter.com/puerco/status/1598484226902560776)). This can be turned off by specifying `--version=false`
2 .  A new `--purl` flag will display purls instead of names for each node in the SBOM graph (when available):
None
```release-note
- `bom document outline` now displays version numbers along package names by default. This can be turned off with `--version=false`
- The `oultine` subcommand has a new `---purl` flag which will display purls instead of package names when outlining an SBOM
```
=> Versions and purls in document outliner

pkg/query/filter_test.go, pkg/spdx/gomod.go, pkg/spdx/implementation.go, pkg/spdx/package.go, pkg/spdx/package_test.go, pkg/spdx/spdx.go
/kind cleanup
This PR modifies `bom` to support the ingestion of external references with both `PACKAGE-MANAGER` and `PACKAGE-MANAGER` in the category field. In SPDX 2.3 it was changed and the agreement during the tech call was to support both cases. 
This change echoes the same [change already done in the SPDX java tools](https://github.com/spdx/tools-java/pull/76/files#diff-2d62de45a362cf43a5c97c9481212a3f8b485b8488aeea7415fb5b7b5dfc2d8cL325).
None
```release-note
SBOM ingestion now supports external references with both `PACKAGE-MANAGER` and `PACKAGE-MANAGER` in the category field. Output is always SPDX 2.3 which calls for `PACKAGE-MANAGER` in the schema.
```
=> Purl(): Support both PACKAGE-MANAGER and PACKAGE-MANAGER

pkg/spdx/implementation.go
Fix https://github.com/kubernetes-sigs/bom/issues/215 by using tag obtained earlier using repo context.
```release-note
Fixed a bug where `bom` would panic when generating an SBOM of an image specified with a digest.
```
=> Fix issue 215

pkg/license/catalog.go, pkg/license/download.go
/kind bug
This PR fixes a bug that broke the license downloader. The downloader cache was being 
called at the wrong place and always returned null data.
It also fixes an unreported bug where download errors were being handled wrong and changes the 
hashing algorithm for cache entries from sha1 to sha256.
NONE
The main bug fix is in e85ab924cb760d7308793e4df74e03e246b74826
```release-note
Fixed a bug where the license downloader was always returning nil data leading to licenses not being detected.
```
=> Fix bug breaking license downloads

pkg/spdx/spdx.go
/kind bug
This commit fixes a bug in the `recursiveIDSearch()` function of the SPDX package to detect recursion loops when searching for SPDX IDs. This fixes a bug where bom would panic when generating an image with an image and a file.
Fixes #240
```release-note
Fixed a recursion loop in `spdx.recursiveIDSearch` which lead to panics when generating sboms describing multiple artifacts.
```
=> Detect recursion loop in spdx.recursiveIDSearch

pkg/serialize/serialize.go, pkg/spdx/implementation.go, pkg/spdx/json/v2.2/types.go, pkg/spdx/json/v2.3/types.go
/kind cleanup
A number of fields in the SPDX 2.3 spec are now optional and allow for less verbose SBOMs when not needed. This PR makes the license fields and package verification `omitempty`able to remove non-required fillds from the final document.
It also improves how we specify the concluded license in files: When the license scanner picks up a license _inside_ a file (ie in the copyright boilerplate) it will now be listed in the licenseConcluded field as it should be.
Fixes #230 
While writing this PR I may have stumbled upon a type on the SPDX JSON schema. Opened https://github.com/spdx/spdx-spec/issues/842 to check.
```release-note
- licenseDeclared in packages and licenseConcluded in files and packages will now be omitted in SPDX 2.3 documents.
- [API Change] the …
```
=> Improve handling of 2.3 optional fields

pkg/serialize/serialize.go, pkg/spdx/document.go
/kind bug
This commit changes the tool string to add the tool version in the document Creator version. It will now pick up the tag+commit version when building a non-tagged version or "devel" when running without tags.
Fixes #235
\
```release-note
- Fixed a bug where the tool version was not getting included in the document creator info. The new Creator field has the app name, version tag and commit: ``bom-v0.4.1-102-g98baf66
```
=> Change tool string to include version

cmd/bom/cmd/generate.go, pkg/license/catalog.go, pkg/license/implementation.go, pkg/license/license.go, pkg/serialize/serialize.go, pkg/spdx/builder.go, pkg/spdx/builder_implementation.go, pkg/spdx/document.go, pkg/spdx/implementation.go, pkg/spdx/spdx.go
/kind feature
In order to make the license list embeddable (see https://github.com/kubernetes-sigs/bom/pull/195), we need to tell the license downloader and catalog which version to use. This PR adds a new flag to `bom generate` to add a new flag `--license-list-version` to configure which version to use.
Right now, the value is hard coded to the latest right no (3.20). Going forward what we want is to embed the data in bom and only download if we need another one.
In order to keep it current, we plan add a new presubmit to ensure at PR time that we are always embedding the latest one from the SPDX license repo.
Related to #195
/cc @sbs2001 
```release-note
- bom will now correctly register in the SBOM the license list it used to scan code to detect licenses
- the version of the SPDX …
```
=> Make license list version configurable

.github/workflows/docs.yml, .github/workflows/verify-spdx.yaml, .ko.yaml, cloudbuild.yaml, go.mod, magefile.go
/kind cleanup
/kind feature
- Upgrade to go1.20
- format indentation 
- using golang image becasue that have all platforms the one before just have two for now when have more we move back
- update golangci and ko
/hold
/assign @puerco @saschagrunert @xmudrii 
None
```release-note
Upgrade to go1.20
```
=> Upgrade to go1.20

.goreleaser.yml
/kind cleanup
- update release binary name
on v0.5.0 release the binary name is like `bom-amd64-darwin_0.5.0_darwin_amd64` which is not good changing to `bom-arm-linux`
rehearsal https://github.com/cpanato/bom/releases/tag/v99.99.02 
/assign @puerco @saschagrunert @ameukam 
None
```release-note
NONE
```
=> update release binary name

pkg/spdx/document_unit_test.go, pkg/spdx/parser.go
/kind bug
/kind cleanup
This PR modifies the encoding detection function to read
the as much of the SBOM as required to detect the encoding.
Some tools (notably [Microsoft's `sbom-tool`](https://github.com/microsoft/sbom-tool)) put the document
creation data at the end of the document and we could not detect it by reading just a few bytes from the top. 
I pushed another commit removing some debugging output I accidentally checked in.
None
```release-note
- bom will now read the SBOM until it detects the SBOM encoding data, enabling it to parse SBOMs with the document data defined at the end of the file.
- When trying to ingest a CycloneDX document, bom will now print a more useful warning 
```
=> Keep reading SBOM until encoding is found

cmd/bom/cmd/document.go, pkg/spdx/parser.go
/kind feature
`bom` will now autodetect when STDIN is open to outline an SBOM.
This avoids typing a dash at the end of the cli invocation and you can just pipe it directly:
`cat sbom | bom document outline`
```release-note
`bom` will now autodetect when STDIN is open to outline an SBOM to avoid specifying it with a dash
```
=> Outliner: Autodetect open STDIN

pkg/osinfo/container_scanner.go, pkg/spdx/implementation.go
/kind feature
This PR adds a new `DownloadLocation()`` function to the `osinfo.PackageDBEntry` type which can generate a download location for system packages which can be used in the SBOM. It will now be used there when it is not an empty string.
None
```release-note
OS Packages now can include an auto-generated download location. Initially supports Debian and Wolfi. 
```
=> OSInfo: Add support for download location

pkg/osinfo/container_scanner_test.go, pkg/serialize/serialize.go, pkg/spdx/json/v2.2/types.go, pkg/spdx/json/v2.3/types.go
/kind bug
This PR modifies the json serializer to add the supplier and originator data. It seems that we forgot to add it to the type and SBOMs encoded in JSON were missing the supplier info. It's there now:
```json
{
"SPDXID": "SPDXRef-Package-SPDXRef-Package-index.docker.io-library-debian-f5802c738e07905ae30f1006c922c1cce3a4955574751a44d5344e9cefabca8c-sha256-015f7b32198b1c57333fa9e151a0b54ccfe05dfef57e98b87c27d426f134db80-66d94da4-a71b-40b7-adc6-6d927d0f47e1",
"name": "libp11-kit0",
"versionInfo": "0.24.1-2",
"filesAnalyzed": false,
"supplier": "Person: Debian GnuTLS Maintainers (pkg-gnutls-maint@lists.alioth.debian.org)",
"copyrightText": "NOASSERTION",
"checksums": [],
"externalRefs": [
{
"referenceCategory": "PACKAGE-MANAGER",
"referenceLocator": …
```
=> Add Supplier Support in JSON encoded SBOMs

cmd/bom/cmd/document_query_printers.go, pkg/spdx/parser.go
/kind cleanup
/kind feature
SPDX supports defining the top-level elements of the SBOM using the `documentDescribes` field but also by linking elements to the document with a `DESCRIBES` relationship. This commit adds support to the JSON parser to detect top-level elements specified using the former method.
I'm also sneaking in a small change to improve printing the licenses in query results. `bom` will now detect better when licenses are `NOASSERTION` when choosing which licenses to print.
None
/assign @cpanato @saschagrunert @xmudrii 
```release-note
- The `bom` json parser now supports top-level elements specified with a `DESCRIBES` relationship to the document. …
```
=> JSON Parser: Support top-level elements defined with relationships

.golangci.yml, go.mod, go.sum, magefile.go
/kind cleanup
- use the default golangci-lint from release-utils
/assign @saschagrunert @puerco @Verolop 
None
```release-note
NONE
```
=> use the default golangci-lint from release-utils

pkg/osinfo/container_scanner.go, pkg/osinfo/container_scanner_test.go, pkg/osinfo/layer_scanner.go, pkg/osinfo/layer_scanner_test.go, pkg/osinfo/scanner_alpine.go, pkg/osinfo/scanner_debian.go, pkg/spdx/implementation.go
This change starts to move individual OS type logic out to individual implementations and files.
/kind cleanup
This change will make it easier to write and test new OS types for `bom generate --scan-images`
None
I tried to keep the `osinfo` package API as close to the same as possible. I made the `containerScanner` and `layerScanner` interfaces and their implementations internal to the package as they're not currently used externally. 
```release-note
NONE
```
=> Refactor osinfo Container Scanner

pkg/license/licensefakes/fake_downloader_implementation.go, pkg/osinfo/container_scanner.go, pkg/osinfo/scanner_alpine.go, pkg/osinfo/scanner_debian.go
/kind bug
The tool was outputting invalid purl types. I looked at using [github.com/package-url/packageurl-go](https://github.com/package-url/packageurl-go), but it is missing types (like `apk`, opend package-url/packageurl-go#63) defined in [the spec](https://github.com/package-url/purl-spec/blob/master/PURL-TYPES.rst).
None
N/A
```release-note
NONE
```
=> fix(osinfo): Fix package URL type for OS packages

.github/workflows/docs.yml
/kind cleanup
The docs GitHub workflow has been failing for some time with a git error. This updates the workflow file so:
- We can get new logs showing what this git failure is; and
- We get the docs job to run if there are configuration changes to the workflow itself
Assuming this shows what the previous failures are from, there may be additional updates needed to correct that root cause. A temporary debugging step has been included to help understand what is happening and will be removed as a follow up.
None
```release-note
NONE
```
=> Trigger docs workflow on changes to workflow config file

magefile.go
See https://goreleaser.com/deprecations/#-skip
Per output of `go run mage.go buildBinariesSnapshot`
/kind bug
/kind  cleanup
Fixes deprecation warning in `magefile`
None
No
```release-note
NONE
```
=> Fix goreleaser --skip-sign deprecation

magefile.go
Updates zeitgeist to v0.4.3 to fix version check
Tested via go run mage.go
/kind bug
Fixes local (non-ci) builds using default mage target
None
See: kubernetes-sigs/zeitgeist#739 and kubernetes-sigs/release-utils#96
If you have an existing version of zeitgeist before 0.4.3 you will have to do `rm $GOPATH/bin/zeitgeist` before `go run mage.go` 
```release-note
NONE
```
=> Fix mage verify

.github/dependabot.yml, .github/workflows/release.yml
/kind cleanup
- group dependabot updates 
- update setup-tejolote to use new home
/assign @Verolop @puerco @xmcqueen @ameukam 
None
```release-note
- group dependabot updates 
- update setup-tejolote to use new home
```
=> Updates for dependabot and release job

cloudbuild.yaml
/kind cleanup
This PR bumps the builder image to go 1.22 
This should fix [image builds](https://github.com/stacklok/minder/actions/runs/8517196913/job/23327380715?pr=2892).
/cc @cpanato @saschagrunert @xmudrii 
```release-note
Builder image updated to `latest-go1.22-bookworm`
```
=> Bump builder image to go1.22-bookworm

.github/workflows/verify-spdx.yaml
/kind cleanup
- update license data to v3.24.0
/assign @puerco @saschagrunert @xmudrii 
None
```release-note
update license data to v3.24.0
```
=> update java-spdx to 1.1.8

pkg/license/download.go
`sha256.New().Sum(foo)` appends the SHA-256 hash for nil to foo. See https://go.dev/play/p/vSW0U3Hq4qk
/kind bug
Honestly, you probably don't _need_ it but the current behavior of defining a cache filename as `$URL + SHA256("")` is silly. This would be an actual bug if y'all weren't using `MkdirAll` to build out the path, but you are.
None
That's a good shirt.
```release-note
Cache filenames generated by the license downloader will now be derived from a SHA256 digest of the URL, rather than the URL itself + SHA256("")
```
=> Use the correct form of `sha256.Sum256`.

cloudbuild.yaml
/kind cleanup
- update cloudbuild job to use go1.24 and fix deprecated field
/assign @puerco @saschagrunert @xmudrii 
None
```release-note
update cloudbuild job to use go1.24 and fix deprecated field
```
=> update cloudbuild job to use go1.24 and fix deprecated field

.github/workflows/docs.yml, .github/workflows/release.yml, .github/workflows/snapshot.yml, .github/workflows/verify-spdx.yaml, .goreleaser.yml
/kind cleanup
our previous releases are using the binary format `bom-<arch>-<os>` but the last one `v0.7.0` the format was `bom-amd64-darwin_0.7.0_darwin_amd64`
this pr fix to use the previous format, after this will cut a new release
/assign @saschagrunert @puerco 
None
```release-note
NONE
```
=> fix release binary name
