- README.md
Signed-off-by: Christopher Angelo Phillips <christopher.phillips@anchore.com>
Add docs clarity for installation.
See Screenshot for updated install command that works
NONE
> update docs with new install instruction

- cmd/bom/cmd/document.go
- cmd/bom/cmd/generate.go
- pkg/spdx/parser.go
/kind cleanup
- don't add duplicate licenses 
- if the file is invalid don't crash 
example
```
$ ./main document outline RELEASE.md
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x13fd34a]
goroutine 1 [running]:
sigs.k8s.io/bom/pkg/spdx.OpenDoc({0x7ff7bfeff3e8, 0xa})
/Users/cpanato/code/src/sigs.k8s.io/bom/pkg/spdx/parser.go:279 +0x2c4a
sigs.k8s.io/bom/cmd/bom/cmd.glob..func1(0x18767c0, {0xc0002195c0, 0x1, 0x1})
/Users/cpanato/code/src/sigs.k8s.io/bom/cmd/bom/cmd/document.go:66 +0x90
github.com/spf13/cobra.(*Command).execute(0x18767c0, {0xc000219590, 0x1, 0x1})
/Users/cpanato/code/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:856 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0x1876cc0) …
```
> small fixes in the code base

- docs/create-a-bill-of-materials.md
> Fix a small typo in sbom guide

- docs/create-a-bill-of-materials.md
> replace references to --directory with --dirs

- README.md
> Fix "bom generate" command usage section in README

- docs/create-a-bill-of-materials.md
> Add --archive and --image-archive usage in README

- magefile.go
/kind feature
This PR will upgrade the ko version from 0.9.3 to 0.10.0 to utilize KOCACHE feature for much more efficient builds
```release-note
feat: upgrade ko, utilize KOCACHE
```
cc: @cpanato @puerco
> feat: upgrade ko, utilize KOCACHE

- docs/yaml_config.md
Signed-off-by: Shivam Sandbhor <shivam.sandbhor@gmail.com>
Adds docs for yaml config.
Fixes https://github.com/kubernetes-sigs/bom/issues/48
I'm not clear on the purpose and working on `external-docs` config. So this is still wip.
```release-note
NONE
```
> Add docs for YAML config

- cmd/bom/cmd/root.go
- magefile.go
/kind cleanup
update version font and ko version
/assign @puerco 
None
```release-note
NONE
```
> update version font and ko version

- canary/images/k8s-staging-bom/images.yaml
- canary/manifests/k8s-staging-bom/promoter-manifest.yaml
/kind feature
We now promote canary images for bom prereleases
/assign @cpanato 
```release-note
We now have image promotion manifests for canary jobs
```
> Add canary image promotion jobs

- canary/manifests/k8s-staging-bom/promoter-manifest.yaml
Push to temporary registry to test svc account identities
```release-note
NONE
```
> Use temporary registry location

- magefile.go
- pkg/provenance/predicate.go
- pkg/provenance/predicate_test.go
- pkg/provenance/provenance.go
- pkg/provenance/statement.go
- pkg/provenance/statement_test.go
/kind cleanup
A new approach to replace the pkg/errors dependency on a package-by-package basis. Concerned packages for this PR:
[pkg/provenance](https://github.com/kubernetes-sigs/bom/tree/main/pkg/provenance)
[magefile.go](https://github.com/kubernetes-sigs/bom/blob/main/magefile.go)
Refers to: https://github.com/kubernetes-sigs/bom/issues/114
None
```release-note
None
```
> Replace pkg/errors dependency

- pkg/osinfo/container_scanner.go
- pkg/osinfo/layer_scanner.go
/kind cleanup
The PR updates the `pkg/osinfo` go packege to replace `github.com/pkg/errors dependency` with native error wrapping
Part of https://github.com/kubernetes-sigs/bom/issues/114
```release-note
NONE
```
> pkg/osinfo: replace github.com/pkg/errors dependency with native error wrapping

- magefile.go
- pkg/provenance/predicate_test.go
- pkg/provenance/statement_test.go
/kind cleanup
A new approach to replace the pkg/errors dependency on a package-by-package basis. Concerned packages for this PR:
[pkg/provenance](https://github.com/kubernetes-sigs/bom/tree/main/pkg/provenance)
[magefile.go](https://github.com/kubernetes-sigs/bom/blob/main/magefile.go)
Refers to: https://github.com/kubernetes-sigs/bom/issues/114
None
```release-note
None
```
> Fix import pkg/errors

- magefile.go
/kind feature
```release-note
feat: use mage pkg to generate ldflags
```
> feat: use mage pkg to generate ldflags

- README.md
Broken link fix
Fix ["Generating a Bill of Materials for Your Project"](https://github.com/kubernetes-sigs/bom/blob/main/docs/create-a-bill-of-materials.md) tutorial link path in README.md
None
```release-note
NONE
```
> Fix create sbom tutorial  link path in README.md

- pkg/spdx/json/document/document.go
- pkg/spdx/json/v2.2/types.go
- pkg/spdx/json/v2.3/types.go
- pkg/spdx/parser.go
/kind cleanup
This make using reflection unnecessary while relying on the implemented interface by both SPDX versions.
Follow-up on https://github.com/kubernetes-sigs/bom/pull/157
cc @puerco 
```release-note
None
```
> Introduce SPDX document interface

- docs/content/en/Tutorials/creating_bill_of_materials.md
Fixes generate command in tutorial doc
> fix generate command in tutorial doc

- pkg/spdx/gomod.go
/kind bug
In golang codebases, bom will die when no go.sum file exists.
This should not happen, it only means that the project is not pulling external modules.
This commit fixes the go package generation to return an empty deps list when encountering such a repo.
Thanks to @strongjz for reporting!
None
```release-note
When indexing golang repos, `bom` would throw a fatal error if no `go.sum` file was found. Now it returns an empty dependency list and generates the SBOM from the repository correctly.
```
> Don't die if no go.sum file exists

- docs/content/en/CLI Reference/bom_version.md
PR replaces `generate` with `version` in CLI reference.
No
> replace generate with version in CLI reference

- magefile.go
- scripts/verify-build.sh
/kind feature
- Add checksums binaries
/assign @saschagrunert @puerco @xmudrii @ameukam @Verolop 
None
```release-note
Add checksums binaries
```
> Add checksums binaries

- pkg/spdx/gomod.go
- pkg/spdx/gomod_test.go
Fix https://github.com/kubernetes-sigs/bom/issues/169
> Fix golang purls

- .ko.yaml
/kind feature
```release-note
replace the registry with cgr.dev
```
> replace the registry with cgr.dev

- pkg/spdx/object.go
/kind cleanup
This commit simplifies the file Checksum function but more importantly removes an unnecessary file open that seemed to be there from a previous version of the code.
None
/assign @cpanato @saschagrunert @sbs2001 
```release-note
Fixed a bug where bom would open each file unnecessarily when checksumming
```
> Refactor file checksum fn

- go.mod
- pkg/license/download.go
- pkg/license/implementation.go
Inital impl of https://github.com/kubernetes-sigs/bom/pull/195#issuecomment-1322442504 .
Need to figure out what would be the best way to pass license list version and refactor the code accordingly.
> Download license zip instead of following links

- README.md
The directions for how to generate an SBOM from the current directory were incorrect. This commit rectifies the guidance.
None
```release-note
NONE
```
> Fix example directions

- README.md
- docs/content/en/Quick Start/_index.md
This commit updates the install instructions to actually work :)
Thanks @jspeed-meyers!
Fixes #214
```release-note
Corrected the go install instructions to install the latest version
```
> Update install instructions

- .bom-config.yaml
- .github/workflows/release.yml
- .github/workflows/snapshot.yml
- .gitignore
- .goreleaser.yml
- cloudbuild.yaml
- go.mod
- go.sum
- magefile.go
- pkg/spdx/builder_implementation.go
- pkg/spdx/file.go
- pkg/spdx/gomod.go
- pkg/spdx/imageanalyzer_gorunner.go
- pkg/spdx/implementation.go
- pkg/spdx/package.go
/kind feature
refactor release to sign the binaries and dogfood the generation of the bom :)
rehearsal here https://github.com/cpanato/bom/releases/tag/v99.99.01
/assign @saschagrunert @puerco @xmudrii 
None
```release-note
NONE
```
> refactor release

- .github/workflows/release.yml
/kind feature
- add attestation in the release job
/assign @puerco @saschagrunert @Verolop 
None
```release-note
add attestation in the release job
```
> add attestation in the release job

- pkg/spdx/implementation.go
/kind bug
This PR fixes a race condition caused by a variable scope creep in the file processor when scanning directories.
Fixes https://github.com/kubernetes-sigs/bom/issues/308
```release-note
Fixed a race condition where concurrent files canning processes could clash and cause a segfault (thanks to @howardjohn for reporting)
```
> Fix variable scope creep in SPDX file processor

- cloudbuild.yaml
/kind cleanup
Using the latest bookworm build image.
None
None
```release-note
None
```
> Use bookworm as go build image

- pkg/osinfo/scanner_rpm.go
/kind bug
RPM package versions also include the release in the version. 
N/A
No
```release-note
NONE
```
> fix(osinfo): Fix RPM version reporting

- README.md
- cmd/bom/cmd/generate.go
- docs/content/en/CLI Reference/bom_generate.md
/kind bug
This PR fixes a small typo
Fixes #394 
```release-note
```
> Fix bug in docs

- .github/workflows/release.yml
- .github/workflows/snapshot.yml
- .github/workflows/verify-spdx.yaml
- go.mod
/kind feature
- upgrade to go1.22
/hold for test-infra update
/assign @saschagrunert @Verolop @xmudrii @puerco 
None
```release-note
NONE
```
> upgrade to go1.22

- README.md
/kind cleanup
- remove asciinema tutorial
it is outdated and maybe there is not need for that
/assign @puerco 
not fix but drop :)
Fixes: https://github.com/kubernetes-sigs/bom/issues/367
None
```release-note
NONE
```
> remove asciinema tutorial

- docs/content/en/Quick Start/_index.md
- The installation script used an invalid link to the precompiled `bom` binary.
- We can shorten the installation by using `install (1)` to copy the file to the target location and set the executable attributes in one go.
None
NONE
```release-note
```
> Fix and shorten installation commands for precompiled binary release

- README.md
The example for `bom document outline` piped `stdout` to the `bom document outline -` command, invoking which resulted in the following error:
```
FATA opening doc: unknown SBOM encoding  
```
None
NONE
```release-note
```
> Fix example of `bom document outline` in README.md

- cmd/bom/cmd/document_query.go
Fixes a typo in the `bom document query` usage doc, should be "omitting" instead of "ammitting".
```release-note
```
> Fix typo in `bom document query` usage doc
